apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: ott-platform
data:
  db-host: "${DB_HOST}"
  redis-host: "${REDIS_HOST}"
  kafka-bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS}"
  eureka-host: "${EUREKA_HOST}"
