apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ott-platform
  labels:
    app: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
